on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: korandoru/setup-zig/@v1
        with:
          zig-version: 0.10.0
      - uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          tag: v0.14.0
          platform: linux
          arch: x86_64
      - run: cargo lambda build --release --arm64